### PR TITLE
index: fix test for time.Time change on 1.9

### PR DESCRIPTION
**Pull request by ferhatelmas**

### CODE REVIEW

**Comment by campoy** [comment]
I think we should not be using `reflect.DeepEqual` since comparing unexported fields is weak
Have you considered trying https://github.com/google/go-cmp?

**Comment by mcuadros** [comment]
Yep for this case, will be inserting use cmp, instead of DeepEquals from gocheck

**Comment by ferhatelmas** [comment]
That's a great suggestion, updated. Added two more small improvements as separate commits.

**Comment by ferhatelmas** [comment]
@mcuadros @campoy ping

**Comment by kuba--** [comment]
Hi guys, I suggest to use `os.TempDir()` in `pack_test.go` and `unpack_test.go` (instead of hardcoded "/tmp/"), because windows builds are failing.
```
...
unpack_test.go:20:
    c.Assert(err, IsNil)
... value *os.PathError = &os.PathError{Op:"CreateFile", Path:"/tmp/", Err:0x2} ("CreateFile /tmp/: The system cannot find the file specified.")
```

**Pull request merged**
